apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: godhand-dialogue-classify-v0
  namespace: godhand-paas-test
spec:
  replicas: 1
  selector:
    matchLabels:
      run: godhand-dialogue-classify-v0
  template:
    metadata:
      labels:
        run: godhand-dialogue-classify-v0
        appName: GODHAND-DIALOGUE-CLASSIFY
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node/type
                    operator: In
                    values:
                      - AIDATA
      containers:
      - env:
        - {name: DEPLOY_ENV, value: 'test'}
        name: godhand-dialogue-classify-v0-containers
        image: 镜像地址
        readinessProbe:
         failureThreshold: 3
         httpGet:
           path: /status/readiness
           port: 5000
           scheme: HTTP
         initialDelaySeconds: 20
         periodSeconds: 10
         successThreshold: 1
         timeoutSeconds: 100
        ports:
          - containerPort: 5000
        resources:
          requests:
            cpu:  1000m
            memory: 500Mi
          limits:
            cpu:  4000m
            memory: 1024Mi
      imagePullSecrets:
        - name: godhand-regcred
      volumes:
        - name: host-time
          hostPath:
            path: /etc/localtime
---
apiVersion: v1
kind: Service
metadata:
  name: godhand-dialogue-classify-v0
  namespace: godhand-paas-test
  labels:
    run: godhand-dialogue-classify-v0
spec:
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    run: godhand-dialogue-classify-v0